version: '3.8'

services:
  db:
    image: postgres:15
    container_name: workout-postgres
    restart: always
    environment:
      POSTGRES_DB: workoutdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: workout-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: workoutdb
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: workout-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: workoutdb
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: workout-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: